Create and edit static contents
ikuseiGmbH/smart-village-app-mainserver pull request #269
Opened 2021-12-10 11:32 UTC by donni106

SVA-315

2021-12-10 13:45 UTC, marcometz requested changes

2021-12-10 13:45 UTC, marcometz commented on app/graphql/mutations/create_or_update_static_content.rb
> +        static_content_id = params.delete(:id)
`return if context[:current_user].admin_role?`

2021-12-10 13:45 UTC, marcometz commented on app/graphql/mutations/create_or_update_static_content.rb
> +        static_content_id = params.delete(:id)
filter by role wird nicht gehen, da es für den Typ bisher kein DataProvider gibt

2022-01-13 19:45 UTC, donni106 commented on app/graphql/mutations/create_or_update_static_content.rb
> +        static_content_id = params.delete(:id)
was meinst du hier genau? was geht nicht un weshalb muss was hinzugefügt werden?

2022-01-19 19:34 UTC, donni106 commented on app/graphql/mutations/create_or_update_static_content.rb
> +        static_content_id = params.delete(:id)
added with #281

2022-01-28 10:08 UTC, marcometz approved these changes

2022-02-02 17:43 UTC, merged