Public Confirmation and Delete Controller
ikuseiGmbH/smart-village-app-mainserver pull request #363
Opened 2022-11-21 15:44 UTC by marcometz

Bestätigungsseite und Action, um einen Eintrag über einen E-Mail Link löschen zu können.

http://localhost:4000/confirmation/destroy/c1ff5c74-7069-4127-9e82-8b6eadd5acf6
leitet nach erfolgreicher Löschung um zu
http://localhost:4000/confirmation/confirmed/c1ff5c74-7069-4127-9e82-8b6eadd5acf6
und im Fehlerfall zu
http://localhost:4000/confirmation/error

![Bildschirm­foto 2022-11-21 um 16 36 43](https://user-images.githubusercontent.com/90779/203097196-46d81ba3-8587-47a4-9a9a-6d6a6f64a484.png)
![Bildschirm­foto 2022-11-21 um 16 36 49](https://user-images.githubusercontent.com/90779/203097208-0b3ca13c-9e64-40dc-863b-18787b828280.png)
![Bildschirm­foto 2022-11-21 um 16 37 00](https://user-images.githubusercontent.com/90779/203097210-47bb2170-0d1a-4b4c-a830-d9c932a37ced.png)
![Bildschirm­foto 2022-11-21 um 16 37 46](https://user-images.githubusercontent.com/90779/203097218-5cc3e41e-4a74-4f00-b103-15675aab9c7b.png)

SVA-739

2022-11-22 13:43 UTC, donni106 requested changes

2022-11-22 13:43 UTC, donni106 commented on app/controllers/public_controller.rb
> +  end
not needed in this controller, i will remove it

2022-11-22 13:43 UTC, donni106 commented on app/views/public/confirm_records/error.html.erb
> +</div>
i will adjust this according to the existing doorkeeper error partial

2022-11-22 14:15 UTC, donni106 commented on app/views/public/confirm_records/error.html.erb
> +</div>
5662423

2022-11-22 14:15 UTC, donni106 commented on app/controllers/public_controller.rb
> +  end
81f2abb

2022-11-22 14:17 UTC, donni106 commented
Adjusted renderings:

|error|record|confirmed|
|---|---|---|
|<img width="1505" alt="image" src="https://user-images.githubusercontent.com/1942953/203336741-f3ae9d9e-f776-4399-87ac-a3e7743f28c7.png">|<img width="1507" alt="image" src="https://user-images.githubusercontent.com/1942953/203336755-0208d4cf-c3c3-4bc5-a461-d5c312367a5a.png">|<img width="1502" alt="image" src="https://user-images.githubusercontent.com/1942953/203336774-ec3c72d9-1420-492b-83e5-42a9f6db52ae.png">|

2022-11-22 14:18 UTC, donni106 commented on app/controllers/public/confirm_records_controller.rb
> +    def validate_record_token
TODO by @marcometz:

> sollen wir hier noch was anderes prüfen?
>  - das eine Übergebene E-Mail stimmt?
>  - ein Recaptcha?

2022-11-22 14:37 UTC, marcometz commented on app/controllers/public/confirm_records_controller.rb
> +    @record.destroy
hahaha... da war noch was, was gefehlt hatte :-)

2022-11-22 14:48 UTC, donni106 commented on app/views/public/confirm_records/confirm.html.erb
> +          <%= @record.dates.first.try(:date_end).strftime(t("doorkeeper.authorized_applications.index.date_format")) %>
danke, erledigt

2022-11-23 10:43 UTC, donni106 approved these changes

2022-11-23 10:43 UTC, merged